remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
github: [metadata]
google_analytics: G-6YE4V0N1Y9
title: Ricky Roberson
show_downloads: false
is_project_page: false
is_user_page: false
